# Assignment: Classification

Classification refers to categorizing the given data into classes. For example,
- Given an image of hand-written character, identifying the character (multi-class classification)
- Given an image, annotating it with all the objects present in the image (multi-label classification)
- Classifying an email as spam or non-spam (binary classification)
- Classifying a tumor as benign or malignant and so on

In this assignment, we will be building a classifier to classify emails as spam or non-spam. We will be using the Kaggle dataset [Spam or Not Spam Dataset](https://www.kaggle.com/datasets/ozlerhakan/spam-or-not-spam-dataset?resource=download) for this task. 

**Note**: You cannot load any libraries other than the mentioned ones.




### Data pre-processing
The first step in every machine learning algorithm is to process the raw data in some meaningful representations. We will be using the [Bag-of-Words](https://towardsdatascience.com/a-simple-explanation-of-the-bag-of-words-model-b88fc4f4971) representation to process the text. It comprises of following steps:

- Process emails line-by-line to extract all the words.
- Replace extracted words by their stem (root) word. This is known as stemming and lematization.
- Remove stop words like and, or, is, am, and so on.
- Assign a unique index to each word. This forms the vocabulary.
- Represent each email as a binary vector of length equal to the size of the vocabulary such that the $i^{th}$ element of the vector is 1 iff the $i^th$ word is present in the email.

Here we provide you with the function signature along with the expected functionality. You are expected to complete them accordingly. 

In [85]:
import numpy as np
from numpy import genfromtxt
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

# import nltk 
# nltk.download('stopwords')

# takes an email as an argument
# read email line-by-line and extract all the words
# return list of extracted words
def read_email(email):
    return (email.split())

# takes a list of words as an argument
# replace each word by their stem word
# return list of stem words
def stemming(words):
    ps = PorterStemmer()
    stem_words = []
    for w in words:
        stem_words.append(ps.stem(w))
    return stem_words

# takes a list of stem-words as an argument
# remove stop words
# return list of stem words after removing stop words
def remove_stop_words(stem_words):
    stop_words = set(stopwords.words('english'))
    stem_no_stop_words = []
    for w in stem_words:
        if w not in stop_words:
            stem_no_stop_words.append(w)

    return stem_no_stop_words

# takes a list of stem-words as an argument
# add new words to the vocabulary and assign a unique index to them
# returns new vocabulary
def build_vocabulary(stem_no_stop_words):
    last_value = len(vocabulary)
    for w in stem_no_stop_words:
        if vocabulary.get(w, "null")=="null":
            vocabulary[w]=last_value
            last_value+=1

# takes a list of stem-words and vocabulary as an argument
# returns bow representation
def get_bow():
    return email_bow
        
def text_to_bow(lst,k):        
    for w in lst:
        bow_representation_of_emails[k,vocabulary[w]]+=1
    
# read the entire dataset
# convert emails to bow and maintain their labels
# call function text_to_bow()
def read_data():
    data = genfromtxt('spam_or_not_spam.csv', delimiter=',', skip_header=1, encoding="utf8", dtype=str)
    
    num_of_emails = len(data)  
    global stem_no_stop_words
    stem_no_stop_words = []
    for i in range(0, num_of_emails):
        words = read_email(data[(i,0)])
        stem_words = stemming(words)
        temp_words = remove_stop_words(stem_words)
        stem_no_stop_words.append(temp_words)
        build_vocabulary(temp_words)
    vocabulary_size = len(vocabulary)
    global bow_representation_of_emails
    bow_representation_of_emails = np.zeros((num_of_emails, vocabulary_size+1))
    for i in range(0,num_of_emails):      
        text_to_bow(stem_no_stop_words[i],i)
        if data[(i,1)] == '1' :
            bow_representation_of_emails[i,vocabulary_size]=1
    print(bow_representation_of_emails)
# Globally defining our vocabulary
vocabulary = {}
read_data()

[[ 2.  1. 42. ...  0.  0.  0.]
 [ 0.  0.  4. ...  0.  0.  0.]
 [ 0.  0.  5. ...  0.  0.  0.]
 ...
 [ 0.  0. 11. ...  0.  0.  1.]
 [ 0.  0. 19. ...  0.  0.  1.]
 [ 0.  0. 32. ...  1.  1.  1.]]


### Data Visualization
Let's understand the data distribution
- Visualize the frequency of word-occurence in all the emails(spam + non-spam)
- Visualize the freuency of word-occurence for spam and non-spam emails separately

In [ ]:
import matplotlib.pyplot as plt

# visuallze data distribution
def data_vis():
    vocabulary_size = len(vocabulary)
    frequency_spams  =  [0 for i in range(vocabulary_size)]
    frequency_hams   =  [0 for i in range(vocabulary_size)]
    frequency_total  =  [0 for i in range(vocabulary_size)]
    num_of_emails = len(bow_representation_of_emails)
    for i in range(0,num_of_emails):
        if bow_representation_of_emails[i,vocabulary_size] == 1:
            for j in range(0,vocabulary_size):
                frequency_spams[j] += bow_representation_of_emails[i,j]
                frequency_total[j] += bow_representation_of_emails[i,j]
        else :
            for j in range(0,vocabulary_size):
                frequency_hams[j] += bow_representation_of_emails[i,j]
                frequency_total[j] += bow_representation_of_emails[i,j]

    list_of_words = []
    for word in vocabulary:
        list_of_words.append(word)
#   Visualizing the frequency of word-occurence in all the emails
    plt.plot(list_of_words,frequency_total)
#   Visualizing the freuency of word-occurence for spam emails
    plt.plot(list_of_words,frequency_spams)
#   Visualizing the freuency of word-occurence for non-spam emails
    plt.plot(list_of_words,frequency_hams)
#   Showing the plot 
    plt.show()
    return

data_vis()

### Learn a Classifier
Split the dataset randomly in the ratio 80:20 as the training and test dataset. Use only training dataset to learn the classifier. No test data should be used during training. Test data will only be used during evaluation.

Now let us try to use ML algorithms to classify emails as spam or non-spam. You are supposed to implement [SVM](https://scikit-learn.org/stable/modules/svm.html) and [K-Nearest Neighbour](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html) algorithm available in scikit-learn using the same training dataset for both.

In [88]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm

# split dataset
def split():
    np.random.shuffle(bow_representation_of_emails)
    total_size = len(bow_representation_of_emails)
    class_label = bow_representation_of_emails[:, -1]
    dataset = bow_representation_of_emails[:, :-1] 
    X_train_data = dataset[0 : int(total_size*0.8)]
    X_test_data = dataset[int(total_size*0.8) :]
    Y_train_data = class_label[0 : int(total_size*0.8)]
    Y_test_data = class_label[int(total_size*0.8) :]
    return X_train_data, X_test_data, Y_train_data, Y_test_data

# learn a SVM model
# use the model to make prediction
# return the model predictions on train and test dataset
def svm_classifier(X_train_data, X_test_data, Y_train_data, Y_test_data):
    clf = svm.SVC(kernel='linear') # A Linear Kernel
    clf.fit(X_train_data, Y_train_data)
    svm_test_predictions = clf.predict(X_test_data)
    svm_train_predictions = clf.predict(X_train_data)
    return svm_train_predictions, svm_test_predictions 

# implement k-NN algorithm
# use the model to make prediction
# return the model predictions on train and test dataset
def knn_classifier(X_train_data, X_test_data, Y_train_data, Y_test_data):
    model = KNeighborsClassifier()
    model.fit(X_train_data, Y_train_data)
    knn_train_predictions = model.predict(X_train_data)
    knn_test_predictions = model.predict(X_test_data)
    return knn_train_predictions, knn_test_predictions 

X_train_data, X_test_data, Y_train_data, Y_test_data = split()
svm_train_predictions, svm_test_predictions = svm_classifier(X_train_data, X_test_data, Y_train_data, Y_test_data)
knn_train_predictions, knn_test_predictions = knn_classifier(X_train_data, X_test_data, Y_train_data, Y_test_data)

### Model Evaluation
Compare the SVM and k-NN model using metrics
- Accuracy
- [AUC score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.auc.html)


In [89]:
from sklearn import metrics
from sklearn.metrics import roc_auc_score

# compute accuracy 
def compute_accuracy(true_labels, predicted_labels):
    acc = metrics.accuracy_score(true_labels, predicted_labels)
    return acc

# compute AUC score 
def compute_auc(true_labels, predicted_labels):
    auc = roc_auc_score(true_labels, predicted_labels)
    return auc

test_acc_svm  = compute_accuracy(Y_test_data,svm_test_predictions)
train_acc_svm = compute_accuracy(Y_train_data,svm_train_predictions)
test_acc_knn  = compute_accuracy(Y_test_data,knn_test_predictions)
train_acc_knn = compute_accuracy(Y_train_data,knn_train_predictions)

test_auc_svm  = compute_auc(Y_test_data,svm_test_predictions)
train_auc_svm = compute_auc(Y_train_data,svm_train_predictions)
test_auc_knn  = compute_auc(Y_test_data,knn_test_predictions)
train_auc_knn = compute_auc(Y_train_data,knn_train_predictions)


print(test_acc_svm)
print(train_acc_svm)
print(test_acc_knn)
print(train_acc_knn)


print(test_auc_svm)
print(train_auc_svm)
print(test_auc_knn)
print(train_auc_knn)


# write code to print train and test accuracy and AUC score of SVM and k-NN classifier

0.9917218543046358
0.9987562189054726
0.8741721854304636
0.8839137645107794
0.9709302325581395
0.9964454976303317
0.8102720660860195
0.8185524780299602
